In [36]:
import numpy as np
import random

"""
Exercise 2: Initialization Objective: Implement the initialization step of a genetic algorithm.
"""


def individual(length):
    return np.array([random.randint(0, 1) for _ in range(length)])

In [37]:
def initialize_population(population_size, length):
    return np.array([individual(length) for _ in range(population_size)])

In [45]:
def fitness(population):
    total_sum = (VALUES * population).sum(axis=1)
    scores = (WEIGHTS * population).sum(axis=1)
    scores[total_sum > LIMIT] = 0
    return scores

def fitness1(individual):
    total_sum = (VALUES * individual).sum()
    score = (WEIGHTS * individual).sum()
    if total_sum > LIMIT:
        return 0
    return score

In [46]:
def select_parents(population, fitness_scores):
    sum_of_fitness_scores = fitness_scores.sum()
    probabilities = (fitness_scores / sum_of_fitness_scores) # + 1 ?
    indexes = np.random.choice(POPULATION_SIZE, size=2, replace=False, p=probabilities)
    return population[indexes]

In [47]:
def crossover(parents):
    offspring = np.zeros((parents.shape[1]))
    for i in range(parents.shape[1]):
        if parents[0][i] == parents[1][i]:
            offspring[i] = parents[0][i]
        else:
            offspring[i] = random.randint(0, 1)

    return offspring

In [48]:
def mutate(chromosome, mutation_rate):
    if random.random() <= mutation_rate:
        chromosome = 1 - chromosome
    return chromosome

In [49]:
def genetic_algorithm(population_size, length, generations, mutation_rate):
    population = initialize_population(population_size, length)

    for _ in range(generations):
        # Fitness evaluation
        fitness_scores = fitness(population)

        # Selection
        parents = select_parents(population, fitness_scores)

        # Crossover
        child = crossover(parents)

        # Mutation
        mutated_child = np.array([mutate(chromosome, mutation_rate) for chromosome in child])

        # Replace the population with the new generation
        minimum = fitness_scores.min()
        if fitness1(mutated_child) < minimum:  # why/why not ?
            continue
        for i in range(fitness_scores.shape[0]):
            if minimum == fitness_scores[i]:
                population[i] = mutated_child
                break

    return population

# Test the complete genetic algorithm
POPULATION_SIZE = 10000
LENGTH = 8
GENERATIONS = 100
MUTATION_RATE = 0.1
WEIGHTS = np.array([10, 10, 10, 2, 1, 2, 1, 1])
VALUES = np.array([1, 68, 2, 2, 38, 68, 8, 1])
LIMIT = 10

final_population = genetic_algorithm(POPULATION_SIZE, LENGTH, GENERATIONS, MUTATION_RATE)
print(final_population)

# determine the best individual from the final population and print it out
fitness_score = fitness(final_population)
maximum = fitness_score.max()
print(f"Maximum is {maximum}")
for i in range(0, fitness_score.shape[0]):
    if fitness_score[i] == maximum:
        print(f"Chosen values {final_population[i] * VALUES} with weights {final_population[i] * WEIGHTS}")
        break

[[1 0 0 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 1 1 0]
 [1 0 1 ... 0 0 1]]
Maximum is 23
Chosen values [1 0 2 2 0 0 0 1] with weights [10  0 10  2  0  0  0  1]
